### PR TITLE
Add storj-analytics and events

### PR DESCRIPTION
**Pull request by barbaraliau**
Adds `storj-analytics` and `Added Payment Method` and `Removed Payment Method` events.

@phutchins This will require adding in the env var `SEGMENT_WRITE_KEY` to the secrets list.

### CODE REVIEW

**Review by dylanlott — APPROVED** [review]
LGTM

**Comment by dylanlott** [comment]
Need to fix package.json conflict but other than that it looks good.

**Comment by braydonf** [comment]
Closing as stale

**Comment by braydonf** [comment]
Closing as stale

**Comment by braydonf** [comment]
Closing as stale

**Pull request closed without merging**
